"╦---------------------------------------------------------------------------╗"
"|                           Commentaires                                    |"
"╬---------------------------------------------------------------------------╣"
"|                              14/05/2023                                   |"
"| Commentaire Chargé                                                        |"
"| l'heure du commentaire                                                    |"
"|                                                    Commentaire etudiant   |"
"|                                                    l'heure du commentaire |"
"|                                                                           |"
"|                                                                           |"
"|                                                                           |"
"|                                                                           |"
"|                                                                           |"
"|                                                                           |"
"|                                                                           |"
"|                                                                           |"
"|                                                                           |"
"----------------------------------------------------------------------------╣"
l = "Bonjour Madame comment allez vous ? Bonjour Madame comment allez vous ?Bonjour Madame comment allez vous ?Bonjour Madame comment allez vous ?Bonjour Madame comment allez vous ?Bonjour Madame comment allez vous "
f"Session {1 if 7 == 1 else 0 }"
