 # print(f"╔{'-'*(TAILLE_SCREEN-2)}╗")
        # self.showMenu([["        Quitter ?", TAILLE_SCREEN, "center"]])
        # print(f"╠{'-'*52}╦{'-'*45}╣")
        # self.showMenu([[f"{RED}Oui", 58, "center"],[f"{SUCCESS}Non{WHITE}", 57, "center"]], screen=(TAILLE_SCREEN+20))
        # print(f"╚{'-'*52}╩{'-'*45}╝")